language: python
python:
    - 3.6.2

services:
    - docker

install:
    - docker build -t freesound-datasets-web .
    - docker run -d -p 127.0.0.1:80:80 --name freesound-datasets-web freesound-datasets-web

script:
    - docker ps | grep -q blog
    - python manage.py test

