language: python
python:
    - 3.6.2

services:
    - docker
    - docker-compose

install:
    - docker build -t mtgupf/freesound-datasets-web .
    - docker-compose up

script:
    -  docker-compose run --rm web python manage.py test

