language: python
python:
    - 3.6.2

services:
    - docker
    - docker-compose

before_install:
    - touch freesound_datasets/local_settings.py

install:
    - docker-compose up

script:
    -  docker-compose run --rm web python manage.py test

