language: python
python:
    - 3.6.2

services:
    - docker
    - docker-compose

before_install:
    - grep -v "uwsgi" requirements.txt > requirements_.txt; mv requirements_.txt requirements.txt
    - mv freesound_datasets/local_setting.example.py freesound_datasets/local_settings.py

install:
    - docker build -t mtgupf/freesound-datasets-web .

script:
    -  docker-compose run --rm web python manage.py test

