version: '2'
volumes:
  dbvolume:
services:
  db:
    image: postgres:9.4
    env_file:
      - .env
    volumes:
      - dbvolume:/var/lib/postgresql/data/
  redis:
    image: redis
  web:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/code
      - /static/
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    env_file:
      - .env
    volumes_from:
      - web
    command: celery worker -A freesound_datasets --loglevel=DEBUG --concurrency=${CELERY_CONCURRENCY}
    depends_on:
      - db
      - redis
